### PR TITLE
Can install from a revision hash now.

### LINKED ISSUE #51: Not working on repo with commit hash
Sample package.json:
```json
{
  "name": "test_hash",
  "dependencies": {
    "grunt-cli": "gruntjs/grunt-cli#121f282"
  }
}
```

### LINKED ISSUE #52: npminstall gitbook@2.0.0 failed
* https://github.com/GitbookIO/gitbook/blob/2.0.0/package.json#L16
* https://git.kernel.org/cgit/git/git.git/tree/Documentation/RelNotes/1.7.10.txt#n84

`git clone -b commit-hash` fails on some repository

### PR DESCRIPTION
**Pull request by ibigbug**
- closes #52 
- closes #51

### CODE REVIEW

File: lib/download/git.js [hunk 1]
```diff
@@ -25,7 +25,13 @@ module.exports = function* (pkg, options) {
   const cloneDir = path.join(options.storeDir, '.tmp', uuid());
   yield utils.mkdirp(cloneDir);
   try {
-    yield clone(gitInfo.url, gitInfo.branch, cloneDir, options);
+    try {
+      yield downloadAndExtract(gitInfo.url, gitInfo.branch, cloneDir, options);
+    } catch (err) {
+      options.console.info(`download tarball failed: ${err.message}, try to clone repository now.`);
```
Comment (dead-horse) [inline lib/download/git.js]: `options.console.warn(chalk.yellow(` 吧

File: lib/download/git.js [hunk 2]
```diff
@@ -25,7 +25,13 @@ module.exports = function* (pkg, options) {
   const cloneDir = path.join(options.storeDir, '.tmp', uuid());
   yield utils.mkdirp(cloneDir);
   try {
-    yield clone(gitInfo.url, gitInfo.branch, cloneDir, options);
+    try {
+      yield downloadAndExtract(gitInfo.url, gitInfo.branch, cloneDir, options);
```
Comment (dead-horse) [inline lib/download/git.js]: 判断一下先只有 github 的才做这一步

**Comment by dead-horse** [comment]
1.4.1
